name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Describe the Bug
        Please fill out all required fields below.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I click X, Y happens..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload or paste screenshots if applicable.

  - type: markdown
    attributes:
      value: "## 💻 Desktop Information"

  - type: input
    id: desktop-os
    attributes:
      label: OS
      placeholder: "Windows 11, macOS, etc."

  - type: input
    id: desktop-linux-flavour
    attributes:
      label: Linux Flavour
      placeholder: "Ubuntu, Arch, Fedora, etc."

  - type: input
    id: desktop-browser
    attributes:
      label: Browser
      placeholder: "Chrome, Firefox, Safari, etc."

  - type: markdown
    attributes:
      value: "## 📱 Smartphone Information"

  - type: input
    id: phone-device
    attributes:
      label: Device
      placeholder: "iPhone XR, Samsung S21, etc."

  - type: input
    id: phone-os
    attributes:
      label: Phone OS
      placeholder: "iOS 17, Android 14, etc."

  - type: input
    id: phone-browser
    attributes:
      label: Mobile Browser
      placeholder: "Safari, Chrome, etc."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
