name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Please describe your idea clearly and completely.

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Example: “I'm always frustrated when…”
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: What do you want to happen? Describe the ideal solution.
      placeholder: "I want the app to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: List other approaches or features you have thought about.
      placeholder: "Alternative idea #1..."
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any extra details, notes, or screenshots.
